### ISSUE TITLE
fcitx not disabled when use M-m to bring up which-key menu

### ISSUE THREAD

**Issue by et2010** [cute-jumper/fcitx.el#11]
In spacemacs while in emacs state, when hit M-m to bring up which-key menu, fcitx was not disabled as expected. Here is my fcitx.el setup:

```emacs-lisp
(setq fcitx-use-dbus t)
(fcitx-aggressive-setup)
```
My system is archlinux 64 with emacs 24.5.1, spacemacs 0.105.9

**Comment by cute-jumper** [comment]
Thanks for reporting this! By default, the setup function will only add "C-x" and "C-c" as prefix keys. For temporary workaround, you can add the following line to your init file:

    (fcitx-prefix-keys-add "M-m")

Probably you should create a pull request to add this setting to the Chinese layer in Spacemacs if this prefix key is **VERY** common for Spacemacs users

**Comment by et2010** [comment]
Thanks for your fast reply! It works like a charm.
