### ISSUE TITLE
fcitx-aggressive-setup makes trouble for evil visual action

### ISSUE THREAD

**Issue by lins05** [cute-jumper/fcitx.el#14]
In evil normal mode, key sequences like "v t a" means "select the text between the current cursor position and the first 'a' character". However, this stops working after `(fcitx-aggressive-setup)` is called.

After some digging I found it can be fixed by `(fcitx-read-funcs-turn-off)`, but I'm not sure if this would affect other functionality of fcitx-remote.

**Comment by cute-jumper** [comment]
Thanks for reporting. I can see they are possibly related, but I could reproduce the problem myself. Can you give steps on how to reproduce the problem via `emacs -Q`? Also, your platform and Emacs version.

**Comment by lins05** [comment]
Sorry for missing the details, here they are:

- OS: Mac OSX 10.11.3
- Emacs Version: 24.5.1 from http://emacsforosx.com/
- fcitx.el version: `~/.emacs.d/.cask/24.5.1/elpa/fcitx-20160209.2040`, installed with Cask (also tried the latest fcitx.el from github)

Steps to reproduce:

- Star emacs `/Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_9 -Q`
- M-x load-library "evil"
- M-x evil-mode (at this time "v t a" works fine)
- M-x load-library "fcitx"
- M-x fcitx-aggressive-setup
- Now "v t a" stops working
- M-x fcitx-read-funcs-turn-off
- Now "v t a" works again

**Comment by cute-jumper** [comment]
OK. I can see the problem now. It seems this only occurs when `fcitx-use-dbus` is `nil`(and this is the default setting). It's weird. You can use `(fcitx-read-funcs-turn-off)` now to make Evil usable. 

This feature(`fcitx-read-funcs-turn-on`) is introduce in #12 , but I'm reluctant to document it since I think there might be some problems. It won't affect too much if you remove them. I'll try to see whether we can solve it.

**Comment by lins05** [comment]
Thanks for the quick reply! I'll keep that turned off then.

**Comment by cute-jumper** [comment]
After a quick investigation, no clue so far why this happens. I've disabled the support of `read-*` in the pre-defined setup function. However, it should be fine to enable this if you're on Linux and set `fcitx-use-dbus` to be `t`.

**Comment by cute-jumper** [comment]
The issue should be solved in 
https://github.com/cute-jumper/fcitx.el/commit/085436e8c5c096e1447f3e6edaeae95ea9505540. Please test! Thanks.
