### ISSUE TITLE
能不能扩展支持其他输入法

### ISSUE THREAD

**Issue by feng-li** [cute-jumper/fcitx.el#15]
非常有用的扩展，能不能扩展支持其他输入法，比如libpinyin

**Comment by cute-jumper** [comment]
据我所知 Libpinyin 本身不是一个输入法吧？ fcitx 和 ibus 都有相应的 wrapper。支持其他输入法本身并不难，只需要知道如何通过命令行或者其他接口（比如 dbus）激活/关闭输入法和查询输入法状态即可。

**Comment by cute-jumper** [comment]
@feng-li I'm closing this now. If you are still interested in this topic, l've added a section in the README: https://github.com/cute-jumper/fcitx.el#work-with-other-input-methods . Generally speaking, it is very easy to add support for other input methods.
