### ISSUE TITLE
Add support for counsel-M-x

### ISSUE THREAD

**Issue by jiegec** [cute-jumper/fcitx.el#16]
It is here:https://github.com/abo-abo/swiper/blob/master/counsel.el.

**Comment by cute-jumper** [comment]
I took a look at it and it seems that it uses `smex` behind the scene. So a simple fix in https://github.com/cute-jumper/fcitx.el/commit/23d55e0ee5de9451be6ea491ce431f1af38ad9e9 should solve the problem. Can you try and confirm? Thanks.

**Comment by jiegec** [comment]
I will try it tonight. The message below that fix should be changed as well.

**Comment by cute-jumper** [comment]
Sure. I tend to update the doc after all functions are working as expected.

**Comment by jiegec** [comment]
Okay. And I remember that the counsel-M-x can can work without semx as well. You can look at its source code again to confirm.

**Comment by cute-jumper** [comment]
Oops...You're correct. Then this would not work. I'll need to look again.

**Comment by cute-jumper** [comment]
See https://github.com/cute-jumper/fcitx.el/commit/031a7fcf206be906233722dd23b7abad4bc31933. I reverted the previous change and this commit instruments `ivy-read` instead of `smex`, which should work probably.

**Comment by jiegec** [comment]
It works. Thanks.
