### ISSUE TITLE
Not working as expected when navigating through which-key menu

### ISSUE THREAD

**Issue by et2010** [cute-jumper/fcitx.el#17]
The `M-m` prefix key works great in spacemacs. However there is still an unresolved issue. I'll try to describe it:

In spacemacs, pressing `M-m` in emacs/hybrid state will bring out the which-key menu, hinting on which key to press next in order to get the desired command. And pressing the corresponding key will bring out menu of next level or just run the command, and so on and so on. If I press a wrong key in that process, I can always hit `C-h u` to undo that key and return to last level of menu. However, with latest MELPA version of fcitx.el, When `C-h u` is pressed, the Chinese im tooltip still pops up.

**Comment by cute-jumper** [comment]
See if [this commit](https://github.com/cute-jumper/fcitx.el/commit/550b410cbaf2aca72d29b9549c66c7ee12836478) helps.

**Comment by et2010** [comment]
Thanks, it works like a charm!
