### ISSUE TITLE
Is it possible for fcitx.el to support evil-escape?

### ISSUE THREAD

**Issue by et2010** [cute-jumper/fcitx.el#18]
I was just wondering if this feature could be implemented. If so, that would be great!

**Comment by cute-jumper** [comment]
I don't use `evil-escape` myself. If you're asking that whether it is possible that the "fd" (the key sequence to escape) would not be blocked by fcitx, I'm afraid that the answer is no. However, if you're using some input method inside Emacs, for example, `chinese-pyim`, that possibly can be done.

**Comment by et2010** [comment]
I see, thanks for the clarification. I've jumped ship from `chinese-pyim`. With fcitx and rime, I don't see the point to switch back as long as I'm not using Windows.

**Comment by cute-jumper** [comment]
Closing this now since I'm not able to fix it.
