### ISSUE TITLE
[Feature request] Add support for avy-goto-char-2

### ISSUE THREAD

**Issue by zilongshanren** [cute-jumper/fcitx.el#20]
When editing Chinese in insert state, I would like to use `avy` to jump around, when call `avy-goto-char-2`, it is still use Chinese Input method, I want it to change to English Input Method and switch back when jump action ended.

Thanks.

**Comment by cute-jumper** [comment]
What setup do you use? `fcitx.el` is able to turn off the input method when I use `avy-goto-char-2`.

**Comment by zilongshanren** [comment]
@cute-jumper  I use the default settings of `fcitx.el`

**Comment by cute-jumper** [comment]
Could you give more details? Do you mean `fcitx-default-setup`? What is your key bindings for `avy-goto-char-2`?

**Comment by zilongshanren** [comment]
@cute-jumper 
Sorry, I only add `fcitx-evil-turn-on` in my config, after adding `fcitx-aggressive-setup`, the problem is solved. 

Thanks for your time.
