### ISSUE TITLE
evil 设置问题

### ISSUE THREAD

**Issue by transtone** [cute-jumper/fcitx.el#25]
这个项目非常棒，解决了我在 emacs 的 evil 模式中频繁切换输入法的问题。
但和之前我直接用 `fcitx-remote -c` 相比，它太智能了：在编辑模式开启输入法 --> 一般模式自动关闭 --> 回到编辑模式自动开启。我只想用前一半的功能，也就是按 `ESC` 之后，我希望输入法永久关闭，而不是临时关闭，回到编辑模式也不开启。

也就是说，我只想在 `esc` 的时候触发，在按 `i`, `a` 等进入编辑模式的按键时不再触发

请问如何设置？

**Comment by cute-jumper** [comment]
这种情况建议直接添加关闭函数到对应的 hook 中即可。比如你把 `fcitx--deactivate` 添加到 `evil-normal-state-exit-hook` 上：

```elisp
(add-hook 'evil-normal-state-exit-hook #'fcitx--deactivate)
```

**Comment by jiegec** [comment]
好了，我找到了。

Closes https://github.com/CodeFalling/fcitx-remote-for-osx/issues/17.

**Comment by transtone** [comment]
`#'fcitx--deactivate` 是什么语法，直接复制进 init.el 报错了。

(setq fcitx-active-evil-states nil) 这样设置似乎无效

**Comment by transtone** [comment]
好吧，我用回原来没用fcitx.el之前的设置了：

``` lisp
(defun close-fcitx ()
  (interactive)
  (save-excursion
    (let ((default-directory "/"))
      (shell-command "/usr/local/bin/fcitx-remote -c"))))
(add-hook 'evil-normal-state-entry-hook 'close-fcitx)

```

**Comment by cute-jumper** [comment]
`fcitx--deactivate` 是 `fcitx.el` 中定义的一个函数，但是没有 `autoload`，使用 `(require 'fcitx)` 或者 `(autoload 'fcitx--deactivate "fcitx')` 加载即可。

**Comment by QiuMP** [comment]
只要在自己的配置文件中重写其evil进入的函数即可，这样效率还高一点
   (defun fcitx--active-evil-states-entry ()
          (fcitx--evil-insert-maybe-deactivate))
