### ISSUE TITLE
Latest master hangs emacs

### ISSUE THREAD

**Issue by lins05** [cute-jumper/fcitx.el#27]
- OS: MacOS 10.12 Sierra
- Emacs: 24.5.1
- fcitx.el version: fcitx-20161013.1040 from MELPA

How to reproduce it?

Sometimes emacs seems to be calling fcitx-remote in an endless loop. When it hangs, I run the command ` pstree -p $(pgrep "(Emacs|emacs)")`, and each time it should show a fcitx-remote process with a different pid.

When it happens, the only way I can do is to kill emacs by "pkill -9 Emacs".

(btw I suggest to add a [.github issues template](https://github.com/blog/2111-issue-and-pull-request-templates) to this project to make it easier for people to provide the OS and emacs version when reporting issues).

**Comment by lins05** [comment]
I have to revert back to tag 0.2.2 to avoid this bug.

**Comment by lins05** [comment]
Emm, seems it still happens even if I reverted it back to 0.2.2 .

**Comment by cute-jumper** [comment]
Thanks for reporting. There is no loop in `fcitx.el`. The prefix key features may be calling `fcitx-remote` very frequently, so that may be the reason. Can you try to turn off the feature if you've enabled it?

Also, if it's related to macOS, is it possible be caused by `fcitx-remote-for-osx`?

> btw I suggest to add a .github issues template to this project to make it easier for people to provide the OS and emacs version when reporting issues

Sounds good. I could do that later.

**Comment by lins05** [comment]
@cute-jumper I don't have the prefix key feature enabled. I think it's most likely related to fcitx-remote-for-osx and my recent os update.

**Comment by lins05** [comment]
FWIW I managed to switch emacs im directly (without using an external program) using emacs dynamic modules. https://github.com/lins05/im-select/blob/master/im-select-module.m

**Comment by cute-jumper** [comment]
I'm not sure, but it looks like the original implementation of `fcitx-remote-for-osx`. Maybe you can talk to the guys of `fcitx-remote-for-osx`. Anyway, `fcitx.el` is only a set of front end functions and whatever method used for im switch doesn't matter.
