### ISSUE TITLE
cant close buffer opened from deleted directory

### ISSUE THREAD

**Issue by ponimas** [cute-jumper/fcitx.el#28]
it's not possible to close buffer opened from deleted directory
error is  

> fcitx--active-p-proc: Setting current directory: No such file or directory, /a/a/a/...

**Comment by cute-jumper** [comment]
Sorry for the late reply. Can you give the detailed steps to reproduce the problem?

**Comment by ponimas** [comment]
Sory for the delay.

So detailed steps are:
1.  create temporary directory
    `mkdir /tmp/test`
2. open file in it
    `emacs /tmp/test/test.txt`
3. delete directory
    `rm -rf /tmp/test`
4. now `test.txt` buffer is unclosable

There are other scenarios. E.g following the link to the file in deleted directory from org file.

**Comment by cute-jumper** [comment]
I see. The buffer is now in a non-existent directory, which causes the error. I've pushed a simple fix and let know if it doesn't work.
