### ISSUE TITLE
fcitx-aggressive-setup makes tramp with sudo hangs on 'Sending password'

### ISSUE THREAD

**Issue by xlighting** [cute-jumper/fcitx.el#3]
When I trun on aggressive setup, tramp with sudo will hangs on 'Sending password', I think it is a bug, I like the aggressive method but I need tramp with sudo to edit files as root,  I hope you fix the bug and, to make more people easily get this nice plugin, can you add it to the elpa repository? Thanks

**Comment by cute-jumper** [comment]
Thank you for reporting this bug. I fixed it in commit https://github.com/cute-jumper/fcitx.el/commit/7a068f0a6cb47506b6681f79dcfdb0d734d91b1d.  Let me know if it doesn't work or anything is broken.

As for the elpa repo, are you familiar with that? It's not on my TODO list right now and I guess I would look into the issue of how to put it on elpa a little bit later(I'm not sure when this would happen though). If you know how to do that, maybe you can help me out.:-)

**Comment by xlighting** [comment]
sorry I'm not familiar with the elpa repo 囧, thanks for your nice work  \(^m^)/

**Comment by xuchunyang** [comment]
> I would look into the issue of how to put it on elpa a little bit later(I'm not sure when this would happen though).

For what it's worth, melpa tracks your github default branch (it's `master` by default) and once it finds the branch gets updated, it will build your package in a few hours (it looks like 2~3 hours to me).  You can use a new branch if you don't want melpa to provide newer version of your package, then of course, users won't be able to try out your changes easily with `package.el` and melpa.  melpa-stable tracks git tags, that is, it won't provide new version of your package until you push a new tag.

**Comment by cute-jumper** [comment]
@xuchunyang Yes, but that is how melpa works, right? This package is already in melpa, so I was thinking that @xlighting was asking to put it into GNU ELPA Repo. I'm not sure whether they are the same. For me, I guess it is enough to have fcitx.el in the melpa.

**Comment by xuchunyang** [comment]
Well, I didn't know you are talking about *GNU ELPA*, I also don't have any experience with it.
