### ISSUE TITLE
f q 找不到 “强

### ISSUE THREAD

**Issue by ziyuanjun** [cute-jumper/fcitx.el#31]
如题。
在一行中出现的“强”字不能通过`f q`或者`F q`的方式找到

**Comment by cute-jumper** [comment]
这和 `fcitx.el` 没有关系。你是指 [evil-find-char-pinyin](https://github.com/cute-jumper/evil-find-char-pinyin)?

**Comment by ziyuanjun** [comment]
是的，我发错地方了
