### ISSUE TITLE
fcitx can't be reenable after enter the spacemacs hybrid mode 

### ISSUE THREAD

**Issue by singular78** [cute-jumper/fcitx.el#32]
I use the example setting for spacemacs users in README.

It disable fcitx successfully when I press "M-m" or when I press "ESC" to exit the “hybrid insert mode”, but it can not reenable fcitx after I press "i" to enter “hybrid insert mode”.

**Comment by cute-jumper** [comment]
I can't reproduce it. I have the exact setup and it works. You need to provide more information, such as the OS, and the settings to reproduce the problem step by step. For example, using a bare Spacemacs without any custom settings, how to reproduce this problem. Thanks!

**Comment by singular78** [comment]
I locate the problem by using emacs debuger. I set debug-on-entry to
fcitx--active-evil-state-entry and find the func finally call
process("fcitx-remote" "-o"), but the fcitx-remote fails to enable the
fcitx.

I reinstall the fcitx-remote-for-osx with input-method=general, then the
problem is solved.

Thanks!
