### ISSUE TITLE
fcitx-aggressive-setup: Args out of range: "", 0

### ISSUE THREAD

**Issue by pzh2386034** [cute-jumper/fcitx.el#35]
when i install fcitx
M-x fcitx-aggressive-setup
then the minibuf print:
fcitx-aggressive-setup: Args out of range: "", 0
and fcitx is not work normally
i am use spacemacs base on emacs 24.5

**Comment by cute-jumper** [comment]
Can you paste the backtrace using `M-x toggle-debug-on-error`?

**Comment by pzh2386034** [comment]
Debugger entered--Lisp error: (args-out-of-range "" 0)
  fcitx-check-status()
  fcitx-aggressive-setup()
  call-interactively(fcitx-aggressive-setup record nil)
  command-execute(fcitx-aggressive-setup record)
  execute-extended-command(nil "fcitx-aggressive-setup")
  smex-read-and-run(("toggle-debug-on-error" "package-list-packages" "unhighlight-regexp" "magit-blame-popup" "fcitx-aggressive-setup" "package-install" "package-show-package-list" "package-build-recipe-alist-as-json" "list-input-methods" "toggle-input-method" "find-library" "line-number-mode" "configuration-layer/create-layer" "help" "info" "configuration-layer/update-packages" "configuration-layer/rollback" "cd" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "fcitx-default-setup" "vimish-fold" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "ielm" "life" "mail" "mpuz" "ping" "pong" ...))
  smex()
  call-interactively(smex nil nil)
  command-execute(smex)

THX

**Comment by cute-jumper** [comment]
What operating system are you using? Looks like your fcitx-remote has some problems.

**Comment by pzh2386034** [comment]
Ubuntu14.04
但是我可以正常使用sogou输入法，如何确定fcitx-remote 有没有问题呢？

**Comment by cute-jumper** [comment]
确保在命令行可以使用 `fcitx-remote`。另外你可以尝试执行以下的代码，看下是啥输出：

```
(with-temp-buffer
  (call-process "fcitx-remote" nil t)
  (buffer-string))
```

**Comment by cute-jumper** [comment]
Closing this now since it seems to be not related to `fcitx.el` itself.
