### ISSUE TITLE
Feature request: Add visual indicator for fcitx

### ISSUE THREAD

**Issue by et2010** [cute-jumper/fcitx.el#38]
Could you please consider adding a visual indicator (could be a unicode char, or a pretty symbol) at mode-line for fcitx to show if the input method is on? It will be cool to have that.

Aside from aesthetic reasons, I think it's super useful especially when we use emacs in fullscreen mode.

**Comment by cute-jumper** [comment]
I think fcitx has its own way to show the status of the input method and I don't really use Emacs in fullscreen mode. It won't be hard to implement such a feature though. Just add a function to the mode-line which constantly checks the status of fcitx. I'm kind of busy now, but ll find some time to do that. Or if you could work on that, you're very welcome to submit a PR so that I can review and accept it.

**Comment by et2010** [comment]
我自己写了一个函数用于 spaceline，使用了 `fcitx--active-p` 函数：
```
(spaceline-define-segment fcitx
  "Show whether fcitx is on"
  (when (and active
             (featurep 'fcitx))
    (if (fcitx--active-p)
        (propertize "漢" 'face 'spaceline-python-venv)
      "En")))
```
如下：
**English:**
![default](https://user-images.githubusercontent.com/11584902/29346150-063f3ba2-8276-11e7-9f63-1696b9b4c713.png)
**中文：**
![default](https://user-images.githubusercontent.com/11584902/29346213-56789fbe-8276-11e7-9aab-ae86231b3a85.png)

但是有一个缺点，切换中英文输入法之后，必须输入一个字符才能看到状态的改变。我猜这应该是 `fcitx--active-p` 的特性造成的，有没有什么解决办法呢？

**Comment by cute-jumper** [comment]
这个和 `fcitx--active-p` 应该没有关系。我猜你是用系统快捷键切换输入法的吧？从 Emacs 的角度看，你用这个快捷键对 Emacs 没有任何输入，因此 mode-line 没有更新。解决方法要么是你加一个 timer，不停地检查 `fcitx--active-p`，更新 mode-line；或者你绑定一个按键，这个快捷键对应的 command 调用 fcitx 里面的函数来操纵 fcitx，这样 mode-line 应该就会更新了。

**Comment by et2010** [comment]
是的，就是你说的这种情况。我试试你提到的第二种方法。谢谢！

**Comment by cute-jumper** [comment]
问题是否已经解决？另外，我想了一下，mode-line 自定义还是交给用户自己。不过可以考虑添加关于定义一个命令来操纵 fcitx 的文档。

**Comment by et2010** [comment]
嗯，解决了。用的你所说的第二种方法。谢谢！

**Comment by cute-jumper** [comment]
OK. Closing this now.
