### ISSUE TITLE
Turn off fcitx when current buffer is read only

### ISSUE THREAD

**Issue by et2010** [cute-jumper/fcitx.el#39]
When current buffer is read-only, it makes no sense to input Chinese there. So maybe we should add a predicate for this? Further, can we suppress fcitx totally when we in such buffer, even when we press the toggle key accidentally?

**Comment by cute-jumper** [comment]
Sure, we can add a predicate for read-only buffers. Not sure how well it can play with the existing functions. However, I'm not convinced that by default we should aggressively disable fcitx even when the user explicitly enables it. We can provide such an option though.

**Comment by cute-jumper** [comment]
See the newest commit which adds two new commands, `fcitx-read-only-turn-{on,off}`. Let me know if there is any problem.

**Comment by et2010** [comment]
Thanks! I'll try it and report here.

**Comment by et2010** [comment]
It really works as expected! Thanks!

现在的功能我已经很满意了，之前我如果在开启中文输入法的情况下，调用有道词典，会在 minibuffer 输入，这时是自动切换成英文的，当输入要查的词回车之后，会打开一个buffer显示词条信息，那是一个read-only buffer，但这时因为刚从 minibuffer 退出的缘故，会切换成中文。这是我不想要的行为。

现在这个 toggle 开启之后，就没有这种行为了，在词典buffer也保持英文输入。但是副作用就是当我退出词典 buffer 回到原来 buffer 的时候，不会自动切回中文了。有没有可能让之前中文输入的状态记忆保存到退出词典buffer呢？也就是连续两个甚至多个 buffer 都不需要中文输入，直到回到原来输入中文的 buffer 再切换至中文？

**Comment by cute-jumper** [comment]
你说的这个问题挺复杂的，是目前 `fcitx.el` 实现的一个根本问题。增加一个开关函数很简单，比如这个 read-only 的功能，但是不同功能之间的协作并不容易控制。你说的这个，minibuffer 退出以后自然就要重新开启，然后打开 read-only buffer 之后又关闭了。因为之前 minibuffer 退出的时候已经调用了开启的函数，所以再切换过去的时候就不会再调用了。每个功能只能控制自己当前的状态，并不知道在这之后之前发生了什么，所以解决你说的问题必须要能够不停记录用户操作流程，然后推断当前的 fcitx 应有的状态。目前基于 hook 的实现应该是做不到的。如果同时考虑协调 prefix-keys 的功能，就更复杂了（prefix-keys 是基于 timer，和其他基于 hook 的实现完全不同)。其实类似于你举的这个例子的 bug 会有很多，开启的功能越多越容易出现互相干扰的情况。

临时的解决办法也许是有的，比如每个 buffer 都记录当前的 fcitx 应有的状态，当调用 switch-to-buffer 的时候检查，但这也还有其他问题，我不建议在这边花费太多精力追求完美，除非能从根本上改变当前这个包的实现。如果有好想法，欢迎讨论。

**Comment by et2010** [comment]
> 我不建议在这边花费太多精力追求完美

确实，如果太复杂的话确实有点得不偿失，现在这样已经足够好用了，谢谢您的回复！
