### ISSUE TITLE
关于 fcitx5 使用的问题

### ISSUE THREAD

**Issue by Azureki** [cute-jumper/fcitx.el#47]
我使用的是fcitx5, 安装该包，发现无效。

搜索历史，发现已经支持了。
[feat: add fcitx5 support by custom fcitx-remote-command ](https://github.com/cute-jumper/fcitx.el/commit/c89c90cca6dc148647d8bc7b4766c84ddd988e34)
在这里声称添加了对fcitx5的支持，可是 `defvar fcitx-remote-command "fcixt-remote"` 的意思不是说依然是fcitx-remote而不是fcitx5-remote吗？
是要修改源代码？还是用软链？（我现在的办法是前者）

开这个issue是想问，正确的使用方法是什么？

**Comment by cute-jumper** [comment]
你需要在你的配置中使用
```
(setq fcitx-remote-command "fcixt5-remote")
```

**Comment by Azureki** [comment]
原来是这样啊，我初学emacs没想到。
感谢您的回复。
