### ISSUE TITLE
Hangs emacs with fcitx-remote-for-osx

### ISSUE THREAD

**Issue by CodeFalling** [cute-jumper/fcitx.el#5]
Hello I develop a command line tools in osx called [fcitx-remote-for-osx](https://github.com/CodeFalling/fcitx-remote-for-osx/).It makes `fcitx.el` and `fcitx.vim` works for osx directly.But I meet some troubles and need help.

https://github.com/CodeFalling/fcitx-remote-for-osx/issues/3

When I enable prefix keys related feature of `fcitx.el`,something like `C-xC-f` will hangs emacs.But I couldn't find the reason.

Emacs version:`GNU Emacs 25.0.50.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1112)) of 2015-10-30`

Spacemacs version:`v.0.104.2`

**Comment by cute-jumper** [comment]
fcitx-remote-for-osx looks like a very interesting project! Unfortunately, I don't have OSX myself. Can you toggle the debug feature of Emacs and give the backtrace? Another convenient way is that you can try to use Edebug in function `fcitx--prefix-keys-polling-function`(Just type `C-u C-M-x` inside the function body of `fcitx--prefix-keys-polling-function` to instrument the function). You may need to set the value of `fcitx-prefix-keys-polling-time` to be a little bit larger too.

Maybe someone who is familiar with OSX and Elisp could help.

**Comment by xuchunyang** [comment]
`fcitx-remote-for-osx` looks interesting to me as well. I'm using OSX but don't have much knowledge about it, I'll see what I can do to help.

**Comment by xuchunyang** [comment]
I can't reproduce the issued you described. `fcitx-remote-for-osx` and `fcitx.el` works fine here (that is, <kbd>C-x C-f</kbd> doesn't hang emacs, actually I don't notice any other key sequence hangs emacs). My Chinese input method is Apple's Pinyin ("简体拼音"), and my `fcitx.el` setup is only `(fcitx-default-setup)`.

**Comment by CodeFalling** [comment]
@xuchunyang So fcitx.el works well for you？Maybe it's caused by im or spacemacs？I will try to figure out when I get free.

**Comment by xuchunyang** [comment]
@CodeFalling Yes, works fine. I don't notice any problem so far.

**Comment by xuchunyang** [comment]
> @xuchunyang So fcitx.el works well for you？Maybe it's caused by im or spacemacs？I will try to figure out when I get free.

I probably made a mistake before: `(fcitx-default-setup)` doesn't work for prefix keys such as <kbd>C-x C-f</kbd> (Pinyin is off after <kbd>C-x</kbd>, but is on after <kbd>C-f</kbd>, anyway, emacs doesn't get hanged), maybe I should blame this on `fcitx.el`. 

BTW, `(fcitx-aggressive-setup)` works well for <kbd>C-x C-f</kbd>.

**Comment by CodeFalling** [comment]
@xuchunyang It seems only my emacs got hanged.It works nice most of time.Maybe I did something wrong in my emacs config.Thanks for your help.

**Comment by CodeFalling** [comment]
Finally I found it's my `fish-shell` cause this problem,`(setq shell-file-name "bash")` works for me perfectly!

**Comment by xuchunyang** [comment]
> (fcitx-default-setup) doesn't work for prefix keys such as C-x C-f, ...  maybe I should blame this on fcitx.el.

It works as expected. I totally misunderstood the effect of `fcitx.el` on prefix keys before.

> Finally I found it's my fish-shell cause this problem,(setq shell-file-name "bash") works for me perfectly!

If #7 gets merged, you will not need to set `shell-file-name` anymore.

**Comment by cute-jumper** [comment]
Thank @xuchunyang . @CodeFalling  can you confirm that after merging #7 , the problem is solved now? It seems weird that functions related to evil and minibuffer still work since they are actually using the same mechanism.

**Comment by CodeFalling** [comment]
@cute-jumper So sorry I have no network now.I will confirm it tomorrow evening.

**Comment by xuchunyang** [comment]
I never encounter the problem, i.e., hangs emacs with `fcitx-remote-for-osx`, so I can't tell if it is solved. Everything works as expected to me with both `*-default-setup` and `*-aggressive-setup`.

**Comment by CodeFalling** [comment]
@cute-jumper @xuchunyang Works well without `(setq shell-file-name "bash")` now.
Hope to see it at melpa as soon!
