### ISSUE TITLE
How do I even use fcitx with Emacs at all? Says "No input window"

### ISSUE THREAD

**Issue by oskarkv** [cute-jumper/fcitx.el#51]
Hi!

This is not an issue with fcitx.el, but how do I even use fcitx with Emacs at all? I'm on Linux Mint. I'm trying to use fcitx to type Korean Hangul. It works in the terminal, in the browser, and so on. But in Emacs (graphical) fcitx says "No input window", and it does not work at all. How do I make it work?

**Comment by cute-jumper** [comment]
Have you followed the Arch Linux wiki for this? https://wiki.archlinux.org/index.php/fcitx#Emacs
