### ISSUE TITLE
Can not quit minibuffer which is in minibuffer-inactive-mode

### ISSUE THREAD

**Issue by tangxinfa** [cute-jumper/fcitx.el#57]
I meet a subtle bug looks for a long time, it looks like caused by fcitx.el:

    The emacs is not quit minibuffer automatically, the cursor leave in
    minibuffer and the minibuffer's major mode is `minibuffer-inactive-mode`.
    Such as press "C-x f" then "C-q", the cursor leave in minibuffer in
    `minibuffer-inactive-mode`, the only thing i can do is switch to other buffer.

This bug come and gone occasionally, i try to capture the root cause but with no luck.
When i execute `(fcitx-prefix-keys-turn-off)` today, this bug gone soon:).

My configuration:

    (fcitx-aggressive-setup)

Emacs version:

    GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6) of 2022-12-05

It looks like this bug appears when come to use Emacs-28, Emacs-29 and Emacs-30.

**Comment by yangdaweihit** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已收到您的邮件。
