### ISSUE TITLE
fcitx.el使用百度输入法的一个小问题

### ISSUE THREAD

**Issue by Carter-Pro** [cute-jumper/fcitx.el#9]
在evil中使用fcitx.el时，多次切换普通模式和插入模式后，百度输入法shift切换中英文会失效，希望能改进

**Comment by cute-jumper** [comment]
fcitx.el 和百度输入法没有关系，可能是 [fcitx-remote-for-osx](https://github.com/CodeFalling/fcitx-remote-for-osx) 的问题。cc @CodeFalling

**Comment by CodeFalling** [comment]
@cute-jumper @Carter-Pro 确实存在这个问题，但是在其他输入法上似乎没有类似的表现，看起来更像是百度拼音输入法的问题。。

**Comment by cute-jumper** [comment]
多谢 @CodeFalling 。看起来都没有关系，关闭这个 issue。

**Comment by Carter-Pro** [comment]
@CodeFalling @cute-jumper 多谢，换个输入法试试
